# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 07:43
from __future__ import unicode_literals

import app.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to=app.models.city_picture_destination)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=2000)),
                ('event_privacy', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('event_venue', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('post_date', models.DateTimeField(default=datetime.datetime(2016, 9, 9, 7, 43, 12, 776718, tzinfo=utc), null=True)),
                ('num_likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('organisers_website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brief_description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qualifications_and_skills', models.TextField()),
                ('job_status', models.CharField(max_length=10)),
                ('method_of_application', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('date_posted', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProminentPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.prominent_place_picture_destination)),
                ('description', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to=app.models.transportaion_picture_destination)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('university_website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to=app.models.university_logo_destination)),
                ('description', models.TextField(blank=True)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.City')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=50)),
                ('lastName', models.CharField(blank=True, max_length=50)),
                ('living_in_turkey', models.CharField(max_length=3)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('city_living', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to=app.models.profile_picture_destination)),
                ('gender', models.CharField(max_length=6)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('about_yourself', models.CharField(blank=True, max_length=500)),
                ('interests', models.CharField(blank=True, max_length=500)),
                ('languages', models.CharField(blank=True, max_length=500)),
                ('occupation', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='author_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_organizer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.EventDetails'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_website',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.EventWebsite'),
        ),
        migrations.AddField(
            model_name='event',
            name='users_liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Transportation'),
        ),
    ]
