# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 14:21
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160906_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prominentplace',
            name='Image',
        ),
        migrations.AddField(
            model_name='prominentplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.prominent_place_picture_destination),
        ),
    ]
