# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 01:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160717_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default=datetime.datetime(2016, 7, 18, 1, 1, 9, 629799, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
