# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 07:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160909_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 9, 7, 48, 20, 442151, tzinfo=utc), null=True),
        ),
    ]
