# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20160909_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='users_liked',
        ),
        migrations.AddField(
            model_name='event',
            name='users_liked',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
