# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160718_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_profile',
            field=models.BooleanField(default=False),
        ),
    ]
