# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160909_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='users_liked',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
