# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20160909_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='users_liked',
        ),
        migrations.AddField(
            model_name='event',
            name='users_liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
