# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20160909_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='users_liked',
        ),
        migrations.AddField(
            model_name='event',
            name='users_liked',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
