# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_eventcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcomment',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='comments',
            field=models.ManyToManyField(to='app.EventComment'),
        ),
    ]
