# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160721_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 21, 9, 28, 20, 568512), null=True),
        ),
    ]
