# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 18:37
from __future__ import unicode_literals

import app.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160722_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 22, 18, 36, 59, 842047, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.FileField(null=True, upload_to=app.models.profile_destination),
        ),
    ]
