# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160722_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='author_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 22, 19, 12, 42, 419704, tzinfo=utc), null=True),
        ),
    ]
