# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160722_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 22, 19, 13, 3, 103819, tzinfo=utc), null=True),
        ),
    ]
