# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 00:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160722_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('university_website', models.URLField(blank=True)),
                ('logo', models.FileField(blank=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.City')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 23, 0, 54, 3, 502041, tzinfo=utc), null=True),
        ),
    ]
