# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20160723_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='comment_text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 23, 2, 9, 2, 746100, tzinfo=utc), null=True),
        ),
    ]
