# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 10:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20160723_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='comment_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 23, 10, 38, 25, 123578, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(),
        ),
    ]
