# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20160723_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 27, 8, 51, 47, 229235, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
