# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20160727_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 27, 12, 40, 58, 366606, tzinfo=utc), null=True),
        ),
    ]
