# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20160727_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 27, 17, 47, 47, 126294, tzinfo=utc), null=True),
        ),
    ]
