# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20160909_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreply',
            name='like_color',
            field=models.CharField(default='gray', max_length=20),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='like_color',
            field=models.CharField(default='gray', max_length=20),
        ),
    ]
