# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20160909_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreply',
            name='flag_color',
            field=models.CharField(default='gray', max_length=30),
        ),
        migrations.AddField(
            model_name='forumreply',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='flag_color',
            field=models.CharField(default='gray', max_length=30),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
